version: "3.8"

services:
  fastapi:
    build:
      context: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./mlruns:/mlruns
    environment:
      - MLFLOW_TRACKING_URI=file:/mlruns
    command: uvicorn app.inference_api:app --host 0.0.0.0 --port 8000 --reload

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
