# Nom du projet (doit correspondre à celui sur SonarQube)
sonar.projectKey=Application-DeepLearning-IoT-TimeSeries-Analyze-AnomalyDetection-MLOps-Security
sonar.projectName=Application-DeepLearning-IoT-TimeSeries-Analyze-AnomalyDetection-MLOps-Security

# Répertoire contenant ton code source
sonar.sources=app,scripts,src

# Fichiers à ignorer
sonar.exclusions=**/__pycache__/**,**/*.log

# Encodage
sonar.sourceEncoding=UTF-8

# Adresse de ton serveur local SonarQube (pas SonarCloud !)
sonar.host.url=http://localhost:9000

# Ton token généré depuis l’interface SonarQube (pas celui de SonarLint !)
sonar.login=d5d81ceabe6fb610bbc03e0ba30e561680aad0eb
