sonar.projectKey=hajar200207_Application-DeepLearning-IoT-TimeSeries-Analyze-AnomalyDetection-MLOps-Security
sonar.organization=application-deeplearning-iot-timeseries-analyze-anomalydetection-mlops-security
sonar.sources=app,scripts,src
sonar.python.version=3.10
sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io
